default_email: you@gmail.com
chrome_binary_location: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

autotab_api_key: ... # Go to https://autotab.com/dashboard to get your API key, or
# run `autotab record` with this field blank and you will be prompted to log in to autotab

credentials:
  - name: Google
    login_url: https://accounts.google.com/v3/signin # Optional, defaults to https://{domain}/login
    domains:
    - google.com
    password: ...

  - name: Notion
    domains:
    - notion.so
    - notion.com
    login_with_google: true

  - name: Figma
    domains:
    - figma.com
    password: ...