default_email: you@gmail.com

environment: local # optional, set to "container" to run headless in a container
chrome_binary_location: /usr/local/bin/chromedriver # required if environment is "local"

autotab_email: you@gmail.com # optional, if set will automatically log you in to the autotab extension
autotab_password: ... # optional, password you use to log in to Autotab (password to Google if you use log in with Google)

credentials:
  - name: Google
    login_url: https://accounts.google.com/v3/signin # optional, defaults to https://{domain}/login
    domains:
    - google.com
    password: ...

  - name: Notion
    domains:
    - notion.so
    - notion.com
    login_with_google: true

  - name: Figma
    domains:
    - figma.com
    password: ...